security:
    # https://symfony.com/doc/current/security.html#registering-the-user-hashing-passwords
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        in_memory:
            memory:
                users:
                    admin:
                        password: '$2a$12$oZkNUky8da4tXRgSxpsbVeIzpdUcPXpNC43z6JZFtcc/tiQgBLneq' # admin_password hashed with bcrypt
                        roles: ['ROLE_ADMIN']

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern: ^/login$
            security: false
            form_login:
                login_path: /login
                check_path: /login

        main:
            lazy: true
            provider: in_memory
            form_login:
                login_path: /login
                check_path: /login
            logout:
                path: /logout
                target: /
            # anonymous: true # Remove this line

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, roles: ROLE_ADMIN }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4 # Lowest possible value for bcrypt
                time_cost: 3 # Lowest possible value for argon
                memory_cost: 10 # Lowest possible value for argon
