<?php

namespace App\Controller\Admin;

use App\Entity\Price;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;

class PriceCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Price::class;
    }


    public function configureFields(string $pageName): iterable
    {
        return [
            IdField::new('id'),
            TextField::new('name'),
            TextEditorField::new('description'),
            TextField::new('category'),
            TextField::new('price') -> formatValue(function ($value) {
                return '$' . $value;
            }),
            TextField::new('unit') -> formatValue(function ($value) {
                return 'per ' . $value;
            }),


        ];
    }

    public function configureCrud(Crud $crud): Crud
    {
        return parent::configureCrud($crud); // TODO: Change the autogenerated stub
    }

}
