controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_images:
    path: /assets/img/{filename}

dashboard:
    path: /admin
    controller: App\Controller\Admin\DashboardController::index




homepage:
    path: /
    controller: App\Controller\HomeController::index

aboutpage:
    path: /aboutus
    controller: App\Controller\AboutUsController::index

app_servicies:
    path: /services
    controller: App\Controller\ServiciesController::index

app_prices:
    path: /prices
    controller: App\Controller\PricesController::index

app_our_projects:
    path: /projects
    controller: App\Controller\OurProjectsController::index


app_contact_us:
    path: /contact
    controller: App\Controller\ContactUsController::index

